// This file will be auto-generated by: pnpm db:generate
// For now, here are the manual type definitions

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type OrgType = 'foundation' | 'association' | 'nonprofit' | 'chapter'
export type UserRole = 'owner' | 'admin' | 'staff' | 'finance' | 'member'
export type MembershipStatus = 'pending' | 'active' | 'expired' | 'cancelled' | 'suspended'
export type PaymentStatus = 'pending' | 'processing' | 'succeeded' | 'failed' | 'refunded' | 'cancelled'
export type EventStatus = 'draft' | 'published' | 'cancelled' | 'completed'
export type RegistrationStatus = 'pending' | 'confirmed' | 'cancelled' | 'checked_in' | 'no_show'
export type GrantStatus = 'draft' | 'submitted' | 'under_review' | 'approved' | 'rejected' | 'withdrawn'
export type ContentStatus = 'draft' | 'published' | 'archived'

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          slug: string
          name: string
          legal_name: string | null
          org_type: OrgType
          email: string | null
          phone: string | null
          website: string | null
          address_line1: string | null
          address_line2: string | null
          city: string | null
          state: string | null
          postal_code: string | null
          country: string
          logo_url: string | null
          primary_color: string
          secondary_color: string
          settings: Json
          stripe_customer_id: string | null
          stripe_account_id: string | null
          ein: string | null
          tax_exempt: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          legal_name?: string | null
          org_type?: OrgType
          email?: string | null
          phone?: string | null
          website?: string | null
          address_line1?: string | null
          address_line2?: string | null
          city?: string | null
          state?: string | null
          postal_code?: string | null
          country?: string
          logo_url?: string | null
          primary_color?: string
          secondary_color?: string
          settings?: Json
          stripe_customer_id?: string | null
          stripe_account_id?: string | null
          ein?: string | null
          tax_exempt?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          legal_name?: string | null
          org_type?: OrgType
          email?: string | null
          phone?: string | null
          website?: string | null
          address_line1?: string | null
          address_line2?: string | null
          city?: string | null
          state?: string | null
          postal_code?: string | null
          country?: string
          logo_url?: string | null
          primary_color?: string
          secondary_color?: string
          settings?: Json
          stripe_customer_id?: string | null
          stripe_account_id?: string | null
          ein?: string | null
          tax_exempt?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          email: string
          first_name: string | null
          last_name: string | null
          display_name: string | null
          avatar_url: string | null
          phone: string | null
          address_line1: string | null
          address_line2: string | null
          city: string | null
          state: string | null
          postal_code: string | null
          country: string
          title: string | null
          company: string | null
          bio: string | null
          linkedin_url: string | null
          twitter_url: string | null
          website_url: string | null
          email_notifications: boolean
          sms_notifications: boolean
          stripe_customer_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          first_name?: string | null
          last_name?: string | null
          display_name?: string | null
          avatar_url?: string | null
          phone?: string | null
          address_line1?: string | null
          address_line2?: string | null
          city?: string | null
          state?: string | null
          postal_code?: string | null
          country?: string
          title?: string | null
          company?: string | null
          bio?: string | null
          linkedin_url?: string | null
          twitter_url?: string | null
          website_url?: string | null
          email_notifications?: boolean
          sms_notifications?: boolean
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          first_name?: string | null
          last_name?: string | null
          display_name?: string | null
          avatar_url?: string | null
          phone?: string | null
          address_line1?: string | null
          address_line2?: string | null
          city?: string | null
          state?: string | null
          postal_code?: string | null
          country?: string
          title?: string | null
          company?: string | null
          bio?: string | null
          linkedin_url?: string | null
          twitter_url?: string | null
          website_url?: string | null
          email_notifications?: boolean
          sms_notifications?: boolean
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      organization_members: {
        Row: {
          id: string
          organization_id: string
          profile_id: string
          role: UserRole
          member_number: string | null
          joined_at: string
          show_in_directory: boolean
          directory_bio: string | null
          tags: string[]
          notes: string | null
          custom_fields: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          profile_id: string
          role?: UserRole
          member_number?: string | null
          joined_at?: string
          show_in_directory?: boolean
          directory_bio?: string | null
          tags?: string[]
          notes?: string | null
          custom_fields?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          profile_id?: string
          role?: UserRole
          member_number?: string | null
          joined_at?: string
          show_in_directory?: boolean
          directory_bio?: string | null
          tags?: string[]
          notes?: string | null
          custom_fields?: Json
          created_at?: string
          updated_at?: string
        }
      }
      membership_plans: {
        Row: {
          id: string
          organization_id: string
          name: string
          slug: string
          description: string | null
          price_cents: number
          currency: string
          billing_interval: string
          billing_interval_count: number
          stripe_product_id: string | null
          stripe_price_id: string | null
          features: Json
          max_members: number | null
          is_active: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          name: string
          slug: string
          description?: string | null
          price_cents?: number
          currency?: string
          billing_interval?: string
          billing_interval_count?: number
          stripe_product_id?: string | null
          stripe_price_id?: string | null
          features?: Json
          max_members?: number | null
          is_active?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          name?: string
          slug?: string
          description?: string | null
          price_cents?: number
          currency?: string
          billing_interval?: string
          billing_interval_count?: number
          stripe_product_id?: string | null
          stripe_price_id?: string | null
          features?: Json
          max_members?: number | null
          is_active?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      memberships: {
        Row: {
          id: string
          organization_id: string
          profile_id: string
          plan_id: string
          status: MembershipStatus
          start_date: string
          end_date: string | null
          cancelled_at: string | null
          stripe_subscription_id: string | null
          amount_paid_cents: number | null
          last_payment_at: string | null
          next_payment_at: string | null
          auto_renew: boolean
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          profile_id: string
          plan_id: string
          status?: MembershipStatus
          start_date: string
          end_date?: string | null
          cancelled_at?: string | null
          stripe_subscription_id?: string | null
          amount_paid_cents?: number | null
          last_payment_at?: string | null
          next_payment_at?: string | null
          auto_renew?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          profile_id?: string
          plan_id?: string
          status?: MembershipStatus
          start_date?: string
          end_date?: string | null
          cancelled_at?: string | null
          stripe_subscription_id?: string | null
          amount_paid_cents?: number | null
          last_payment_at?: string | null
          next_payment_at?: string | null
          auto_renew?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      events: {
        Row: {
          id: string
          organization_id: string
          title: string
          slug: string
          description: string | null
          short_description: string | null
          event_type: string
          start_date: string
          end_date: string
          timezone: string
          is_virtual: boolean
          venue_name: string | null
          venue_address: string | null
          venue_city: string | null
          venue_state: string | null
          venue_postal_code: string | null
          virtual_url: string | null
          cover_image_url: string | null
          registration_opens_at: string | null
          registration_closes_at: string | null
          max_attendees: number | null
          is_free: boolean
          member_discount_percent: number
          early_bird_discount_percent: number
          early_bird_deadline: string | null
          status: EventStatus
          settings: Json
          created_at: string
          updated_at: string
          published_at: string | null
        }
        Insert: {
          id?: string
          organization_id: string
          title: string
          slug: string
          description?: string | null
          short_description?: string | null
          event_type?: string
          start_date: string
          end_date: string
          timezone?: string
          is_virtual?: boolean
          venue_name?: string | null
          venue_address?: string | null
          venue_city?: string | null
          venue_state?: string | null
          venue_postal_code?: string | null
          virtual_url?: string | null
          cover_image_url?: string | null
          registration_opens_at?: string | null
          registration_closes_at?: string | null
          max_attendees?: number | null
          is_free?: boolean
          member_discount_percent?: number
          early_bird_discount_percent?: number
          early_bird_deadline?: string | null
          status?: EventStatus
          settings?: Json
          created_at?: string
          updated_at?: string
          published_at?: string | null
        }
        Update: {
          id?: string
          organization_id?: string
          title?: string
          slug?: string
          description?: string | null
          short_description?: string | null
          event_type?: string
          start_date?: string
          end_date?: string
          timezone?: string
          is_virtual?: boolean
          venue_name?: string | null
          venue_address?: string | null
          venue_city?: string | null
          venue_state?: string | null
          venue_postal_code?: string | null
          virtual_url?: string | null
          cover_image_url?: string | null
          registration_opens_at?: string | null
          registration_closes_at?: string | null
          max_attendees?: number | null
          is_free?: boolean
          member_discount_percent?: number
          early_bird_discount_percent?: number
          early_bird_deadline?: string | null
          status?: EventStatus
          settings?: Json
          created_at?: string
          updated_at?: string
          published_at?: string | null
        }
      }
      ticket_types: {
        Row: {
          id: string
          event_id: string
          name: string
          description: string | null
          price_cents: number
          currency: string
          stripe_price_id: string | null
          quantity_available: number | null
          quantity_sold: number
          max_per_order: number
          sales_start_at: string | null
          sales_end_at: string | null
          members_only: boolean
          is_active: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          event_id: string
          name: string
          description?: string | null
          price_cents: number
          currency?: string
          stripe_price_id?: string | null
          quantity_available?: number | null
          quantity_sold?: number
          max_per_order?: number
          sales_start_at?: string | null
          sales_end_at?: string | null
          members_only?: boolean
          is_active?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          name?: string
          description?: string | null
          price_cents?: number
          currency?: string
          stripe_price_id?: string | null
          quantity_available?: number | null
          quantity_sold?: number
          max_per_order?: number
          sales_start_at?: string | null
          sales_end_at?: string | null
          members_only?: boolean
          is_active?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      donations: {
        Row: {
          id: string
          organization_id: string
          profile_id: string | null
          campaign_id: string | null
          donor_email: string
          donor_name: string | null
          is_anonymous: boolean
          amount_cents: number
          currency: string
          is_recurring: boolean
          recurring_interval: string | null
          stripe_subscription_id: string | null
          fund_designation: string | null
          status: PaymentStatus
          payment_id: string | null
          receipt_sent_at: string | null
          thank_you_sent_at: string | null
          notes: string | null
          tribute_type: string | null
          tribute_name: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          profile_id?: string | null
          campaign_id?: string | null
          donor_email: string
          donor_name?: string | null
          is_anonymous?: boolean
          amount_cents: number
          currency?: string
          is_recurring?: boolean
          recurring_interval?: string | null
          stripe_subscription_id?: string | null
          fund_designation?: string | null
          status?: PaymentStatus
          payment_id?: string | null
          receipt_sent_at?: string | null
          thank_you_sent_at?: string | null
          notes?: string | null
          tribute_type?: string | null
          tribute_name?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          profile_id?: string | null
          campaign_id?: string | null
          donor_email?: string
          donor_name?: string | null
          is_anonymous?: boolean
          amount_cents?: number
          currency?: string
          is_recurring?: boolean
          recurring_interval?: string | null
          stripe_subscription_id?: string | null
          fund_designation?: string | null
          status?: PaymentStatus
          payment_id?: string | null
          receipt_sent_at?: string | null
          thank_you_sent_at?: string | null
          notes?: string | null
          tribute_type?: string | null
          tribute_name?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          organization_id: string
          profile_id: string | null
          payment_type: string
          reference_type: string | null
          reference_id: string | null
          amount_cents: number
          currency: string
          status: PaymentStatus
          stripe_payment_intent_id: string | null
          stripe_charge_id: string | null
          stripe_invoice_id: string | null
          payer_email: string | null
          payer_name: string | null
          refunded_amount_cents: number
          refunded_at: string | null
          description: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          profile_id?: string | null
          payment_type: string
          reference_type?: string | null
          reference_id?: string | null
          amount_cents: number
          currency?: string
          status?: PaymentStatus
          stripe_payment_intent_id?: string | null
          stripe_charge_id?: string | null
          stripe_invoice_id?: string | null
          payer_email?: string | null
          payer_name?: string | null
          refunded_amount_cents?: number
          refunded_at?: string | null
          description?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          profile_id?: string | null
          payment_type?: string
          reference_type?: string | null
          reference_id?: string | null
          amount_cents?: number
          currency?: string
          status?: PaymentStatus
          stripe_payment_intent_id?: string | null
          stripe_charge_id?: string | null
          stripe_invoice_id?: string | null
          payer_email?: string | null
          payer_name?: string | null
          refunded_amount_cents?: number
          refunded_at?: string | null
          description?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      work_items: {
        Row: {
          id: string
          organization_id: string
          type: string
          module: string
          title: string
          body: string | null
          priority: string
          status: string
          due_at: string | null
          snoozed_until: string | null
          assignee_profile_id: string | null
          assignee_role: string | null
          reference_type: string | null
          reference_id: string | null
          dedupe_key: string | null
          actions: Json
          created_by_profile_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          type: string
          module: string
          title: string
          body?: string | null
          priority?: string
          status?: string
          due_at?: string | null
          snoozed_until?: string | null
          assignee_profile_id?: string | null
          assignee_role?: string | null
          reference_type?: string | null
          reference_id?: string | null
          dedupe_key?: string | null
          actions?: Json
          created_by_profile_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          type?: string
          module?: string
          title?: string
          body?: string | null
          priority?: string
          status?: string
          due_at?: string | null
          snoozed_until?: string | null
          assignee_profile_id?: string | null
          assignee_role?: string | null
          reference_type?: string | null
          reference_id?: string | null
          dedupe_key?: string | null
          actions?: Json
          created_by_profile_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      saved_views: {
        Row: {
          id: string
          organization_id: string
          module: string
          name: string
          is_shared: boolean
          is_default: boolean
          created_by_profile_id: string
          state: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          module: string
          name: string
          is_shared?: boolean
          is_default?: boolean
          created_by_profile_id: string
          state?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          module?: string
          name?: string
          is_shared?: boolean
          is_default?: boolean
          created_by_profile_id?: string
          state?: Json
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_user_org_ids: {
        Args: Record<string, never>
        Returns: string[]
      }
      is_org_admin: {
        Args: { org_id: string }
        Returns: boolean
      }
    }
    Enums: {
      org_type: OrgType
      user_role: UserRole
      membership_status: MembershipStatus
      payment_status: PaymentStatus
      event_status: EventStatus
      registration_status: RegistrationStatus
      grant_status: GrantStatus
      content_status: ContentStatus
      work_item_type: 'task' | 'alert' | 'approval'
      work_item_module: 'memberships' | 'donations' | 'events' | 'grants' | 'finance' | 'cms' | 'general'
      work_item_priority: 'low' | 'normal' | 'high' | 'urgent'
      work_item_status: 'open' | 'snoozed' | 'done'
      saved_view_module: 'members' | 'donations' | 'events' | 'payments' | 'grants'
    }
  }
}

// Convenience types
export type Organization = Database['public']['Tables']['organizations']['Row']
export type Profile = Database['public']['Tables']['profiles']['Row']
export type OrganizationMember = Database['public']['Tables']['organization_members']['Row']
export type MembershipPlan = Database['public']['Tables']['membership_plans']['Row']
export type Membership = Database['public']['Tables']['memberships']['Row']
export type Event = Database['public']['Tables']['events']['Row']
export type TicketType = Database['public']['Tables']['ticket_types']['Row']
export type Donation = Database['public']['Tables']['donations']['Row']
export type Payment = Database['public']['Tables']['payments']['Row']
export type WorkItem = Database['public']['Tables']['work_items']['Row']
export type SavedView = Database['public']['Tables']['saved_views']['Row']

// Extended types with relations
export type ProfileWithOrgs = Profile & {
  organization_members: (OrganizationMember & {
    organization: Organization
  })[]
}

export type MemberWithProfile = OrganizationMember & {
  profile: Profile
  membership?: Membership
}

export type EventWithTickets = Event & {
  ticket_types: Database['public']['Tables']['ticket_types']['Row'][]
  registrations_count?: number
}

// =====================================================
// EXTENDED TYPES FOR FULL PLATFORM
// =====================================================

// Member Organizations
export type MemberOrganization = Database['public']['Tables']['member_organizations']['Row']
export type MemberOrganizationInsert = Database['public']['Tables']['member_organizations']['Insert']
export type MemberContact = Database['public']['Tables']['member_contacts']['Row']
export type MemberContactInsert = Database['public']['Tables']['member_contacts']['Insert']

// Directory
export type DirectoryCategory = Database['public']['Tables']['directory_categories']['Row']

// Email Marketing
export type EmailList = Database['public']['Tables']['email_lists']['Row']
export type EmailTemplate = Database['public']['Tables']['email_templates']['Row']
export type EmailCampaign = Database['public']['Tables']['email_campaigns']['Row']
export type EmailAutomation = Database['public']['Tables']['email_automations']['Row']

// CMS
export type CmsPage = Database['public']['Tables']['cms_pages']['Row']
export type CmsPost = Database['public']['Tables']['cms_posts']['Row']

// Job Board
export type JobPosting = Database['public']['Tables']['job_postings']['Row']
export type JobApplication = Database['public']['Tables']['job_applications']['Row']

// Forums
export type Forum = Database['public']['Tables']['forums']['Row']
export type ForumTopic = Database['public']['Tables']['forum_topics']['Row']
export type ForumReply = Database['public']['Tables']['forum_replies']['Row']

// Resources
export type ResourceFolder = Database['public']['Tables']['resource_folders']['Row']
export type Resource = Database['public']['Tables']['resources']['Row']

// Social
export type SocialAccount = Database['public']['Tables']['social_accounts']['Row']
export type SocialPost = Database['public']['Tables']['social_posts']['Row']

// Events Extended
export type EventSession = Database['public']['Tables']['event_sessions']['Row']
export type EventSponsor = Database['public']['Tables']['event_sponsors']['Row']
